name: Passkeys Resources Website Deploy CI

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: npm

            - name: Build
              run: |
                  cd website
                  npm ci
                  npm run fetch-domains
                  npm run build
                  touch out/.nojekyll

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  folder: website/out
