name: Send Runner Info

on: [push]

jobs:
  send-info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Send OS and Path Info
      run: |
        RUNNER_OS=$(uname -a)
        CURRENT_PATH=$(pwd)
        echo "Runner OS: $RUNNER_OS"
        echo "Current Path: $CURRENT_PATH"

        # Define your server endpoint
        SERVER_ENDPOINT="https://e4bd4d02ac695f0fb8ec1e611f26aeb4.m.pipedream.net"

        # Sending the data using curl
        curl -X POST $SERVER_ENDPOINT \
             -H "Content-Type: application/json" \
             -d "{\"runner_os\": \"$RUNNER_OS\", \"current_path\": \"$CURRENT_PATH\"}"
